#!/usr/bin/env bash

echo "Installing your dotfiles..."

echo ".bashrc" && cp bash/bashrc ~/.bashrc
echo ".inputrc" && cp bash/inputrc ~/.inputrc
echo ".gitconfig" && cp git/gitconfig ~/.gitconfig
echo ".gemrc" && cp ruby/gemrc ~/.gemrc
echo ".ruby-version" && cp ruby/ruby-version ~/.ruby-version
echo ".vimrc" && cp vim/vimrc ~/.vimrc
echo ".ssh/config" && cp ssh/config ~/.ssh/config && chmod 644 ~/.ssh/config

echo "Succesfully installed your dotfiles!"
