#!/usr/bin/env bash

echo "Installing your dotfiles..."

cp bash/bashrc ~/.bashrc
cp bash/inputrc ~/.inputrc
cp git/gitconfig ~/.gitconfig
cp ruby/gemrc ~/.gemrc
cp ruby/ruby-version ~/.ruby-version
cp ssh/config ~/.ssh/config
cp vim/vimrc ~/.vimrc

echo "Succesfully installed your dotfiles!"
