" Filetype detection
if has("autocmd")
    filetype on
    filetype indent on
    filetype plugin on
endif

" Syntax highlighting
syntax enable
set background=dark
let g:solarized_termtrans=1
let g:solarized_termcolors=256
colorscheme solarized

" Show linenumbers
set number

" Indentation settings
set shiftwidth=2
set softtabstop=2
set expandtab

" Highlight trailing spaces
:highlight ExtraWhitespace ctermbg=darkgreen guibg=lightgreen
